set number
set nocompatible
syntax on
set showmode
set showcmd
set mouse=a
set encoding=utf-8
set t_Co=256
filetype indent on
set autoindent
set tabstop=4
set shiftwidth=4
set cursorline
set nowrap
set laststatus=2
set ruler
set showmatch
set hlsearch
set ignorecase
set smartcase
set nobackup
set noswapfile
set noerrorbells
set visualbell
set history=1000
set autoread
set listchars=tab:»■,trail:■
set wildmenu
set wildmode=longest:list,full
